main: maven-main
version: maven-version
name: maven-name
author: maven-authors
softdepend: [Vault]
api-version: 1.13

commands:
  pwi:
    description: Commands for PerWorldInventory
    aliases: [perworldinventory]
    
permissions:
  perworldinventory.admin:
    default: op
    children:
      perworldinventory.command.convert: true
      perworldinventory.command.export: true
      perworldinventory.command.help: true
      perworldinventory.command.reload: true
      perworldinventory.command.version: true
      perworldinventory.command.groups.list: true
      perworldinventory.command.groups.info: true
      perworldinventory.command.groups.add: true
      perworldinventory.command.groups.modify: true
      perworldinventory.command.groups.remove: true
      perworldinventory.command.migrate: true
  perworldinventory.bypass.*:
    default: false
    children:
      perworldinventory.bypass.gamemode: true
      perworldinventory.bypass.world: true
  perworldinventory.command.convert:
    default: false
  perworldinventory.command.help:
    default: false
  perworldinventory.command.reload:
    default: false
  perworldinventory.command.version:
    default: false
  perworldinventory.command.groups.list:
    default: false
  perworldinventory.command.groups.info:
    default: false
  perworldinventory.command.groups.add:
    default: false
  perworldinventory.command.groups.modify:
    default: false
  perworldinventory.command.groups.remove:
    default: false
  perworldinventory.command.migrate:
    default: false
  perworldinventory.bypass.gamemode:
    default: false
  perworldinventory.bypass.world:
    default: false
